name: 自动构建发布

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install networkx xxhash==3.5.0 joblib tqdm loguru luaparser pyvis PySide6
          pip install pyinstaller==5.13.2
        shell: pwsh

      - name: 创建辅助脚本
        run: |
          $line1 = "import os, sys, pyvis"
          $line2 = "pyvis_dir = os.path.dirname(pyvis.__file__)"
          $line3 = "templates_dir = os.path.join(pyvis_dir, 'templates')"
          $line4 = "print(f'{templates_dir};pyvis/templates')"
          $line1 | Out-File -FilePath "get_pyvis_paths.py"
          $line2 | Add-Content -Path "get_pyvis_paths.py"
          $line3 | Add-Content -Path "get_pyvis_paths.py"
          $line4 | Add-Content -Path "get_pyvis_paths.py"
          
          Get-Content -Path "get_pyvis_paths.py"
        shell: pwsh

      - name: 使用 PyInstaller 打包 GUI 应用
        run: |
          $pyvisDatas = python get_pyvis_paths.py
          Write-Host "Pyvis模板路径: $pyvisDatas"
          
          pyinstaller --name lus4n-gui --onefile --noconsole `
            --hidden-import networkx `
            --hidden-import xxhash `
            --hidden-import joblib `
            --hidden-import tqdm `
            --hidden-import loguru `
            --hidden-import luaparser `
            --hidden-import pyvis `
            --hidden-import PySide6 `
            --hidden-import PySide6.QtWebEngineCore `
            --hidden-import PySide6.QtWebEngineWidgets `
            --hidden-import PySide6.QtWebChannel `
            --collect-all networkx `
            --collect-all pyvis `
            --add-data "$pyvisDatas" `
            lus4n/gui.py
        shell: pwsh

      - name: 使用 PyInstaller 打包 CLI 应用
        run: |
          $pyvisDatas = python get_pyvis_paths.py
          Write-Host "Pyvis模板路径: $pyvisDatas"
          
          pyinstaller --name lus4n-cli --onefile --console `
            --hidden-import networkx `
            --hidden-import xxhash `
            --hidden-import joblib `
            --hidden-import tqdm `
            --hidden-import loguru `
            --hidden-import luaparser `
            --collect-all networkx `
            --collect-all pyvis `
            --add-data "$pyvisDatas" `
            lus4n/cli.py
        shell: pwsh

      - name: 列出构建文件
        run: |
          Write-Host "== 列出dist目录内容 =="
          Get-ChildItem -Path dist -Recurse | Format-Table Name, Length, LastWriteTime
        shell: pwsh

      - name: 准备发布文件
        run: |
          mkdir releases -Force
          
          if (Test-Path "dist\lus4n-gui.exe") {
            Compress-Archive -Path "dist\lus4n-gui.exe" -DestinationPath "releases\lus4n-gui-windows.zip" -Force
            Write-Host "GUI版本打包成功"
          } else {
            Write-Host "找不到GUI可执行文件" -ForegroundColor Red
            Get-ChildItem -Path dist -Recurse | Select-Object FullName
          }
          
          if (Test-Path "dist\lus4n-cli.exe") {
            Compress-Archive -Path "dist\lus4n-cli.exe" -DestinationPath "releases\lus4n-cli-windows.zip" -Force
            Write-Host "CLI版本打包成功"
          } else {
            Write-Host "找不到CLI可执行文件" -ForegroundColor Red
            Get-ChildItem -Path dist -Recurse | Select-Object FullName
          }
        shell: pwsh

      - name: 发布版本
        uses: softprops/action-gh-release@v1
        with:
          name: lus4n ${{ github.ref_name }}
          body: |
            lus4n ${{ github.ref_name }} 发布
            
            ### 包含内容:
            - Windows GUI版本 (lus4n-gui-windows.zip)
            - Windows 命令行版本 (lus4n-cli-windows.zip)
            
            ### 更新内容：
            请参考 readme 文件
          files: |
            ./releases/lus4n-gui-windows.zip
            ./releases/lus4n-cli-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}