name: Auto Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggered when pushing tags with v prefix like v1.2.0
  
jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Create hook file for luaparser
        shell: pwsh
        run: |
          $hookDir = ".\hooks"
          if (!(Test-Path $hookDir)) {
              New-Item -Path $hookDir -ItemType Directory | Out-Null
          }
          
          $luaparserContent = "# PyInstaller hook for luaparser`nfrom PyInstaller.utils.hooks import collect_submodules, collect_data_files`n`n# Make sure all submodules are included`nhiddenimports = collect_submodules('luaparser')`n`n# Include any data files`ndatas = collect_data_files('luaparser')"
          Set-Content -Path "$hookDir\hook-luaparser.py" -Value $luaparserContent
      
      - name: Create hook file for xxhash
        shell: pwsh
        run: |
          $hookDir = ".\hooks"
          $xxhashContent = "# PyInstaller hook for xxhash`nhiddenimports = ['xxhash']"
          Set-Content -Path "$hookDir\hook-xxhash.py" -Value $xxhashContent
          
      - name: Create hook file for PySide6
        shell: pwsh
        run: |
          $hookDir = ".\hooks"
          $pyside6Content = "# PyInstaller hook for PySide6`nfrom PyInstaller.utils.hooks import collect_submodules, collect_data_files`n`n# Make sure all submodules are included`nhiddenimports = collect_submodules('PySide6')`n`n# Specifically include QtWebEngineWidgets which is often missed`nhiddenimports += ['PySide6.QtWebEngineCore', 'PySide6.QtWebEngineWidgets', 'PySide6.QtWebChannel']`n`n# Include any data files`ndatas = collect_data_files('PySide6')"
          Set-Content -Path "$hookDir\hook-PySide6.py" -Value $pyside6Content
          
      - name: Create hook file for pyvis
        shell: pwsh
        run: |
          $hookDir = ".\hooks"
          $pyvisContent = "# PyInstaller hook for pyvis`nfrom PyInstaller.utils.hooks import collect_submodules, collect_data_files`n`n# Make sure all submodules are included`nhiddenimports = collect_submodules('pyvis')`n`n# Include any data files`ndatas = collect_data_files('pyvis')"
          Set-Content -Path "$hookDir\hook-pyvis.py" -Value $pyvisContent
          
      - name: Create global hook file
        shell: pwsh
        run: |
          $hookDir = ".\hooks"
          $globalContent = "# Global hidden imports to ensure all dependencies are included`nhiddenimports = ['xxhash', 'networkx', 'joblib', 'tqdm', 'loguru', 'luaparser', 'setuptools', 'pyvis', 'PySide6', 'PySide6.QtWebEngineCore', 'PySide6.QtWebEngineWidgets', 'PySide6.QtWebChannel', 'uuid', 'tempfile', 'webbrowser']"
          Set-Content -Path "$hookDir\hook-lus4n.py" -Value $globalContent
      
      - name: Package application
        shell: pwsh
        run: |
          # Clean up old output directories
          $outputDirs = @(".\dist", ".\build", ".\releases")
          foreach ($dir in $outputDirs) {
              if (Test-Path $dir) {
                  Remove-Item -Path $dir -Recurse -Force
              }
              New-Item -Path $dir -ItemType Directory | Out-Null
          }
          
          # Get CPU core count for parallel compilation
          $cpuCores = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
          
          # Package GUI application with explicit includes
          Write-Host "Packaging GUI application (using $cpuCores CPU cores)..." -ForegroundColor Green
          pyinstaller --clean --noconfirm --onedir --name "lus4n-gui" --windowed --additional-hooks-dir=hooks `
            --hidden-import=xxhash `
            --hidden-import=networkx `
            --hidden-import=joblib `
            --hidden-import=tqdm `
            --hidden-import=loguru `
            --hidden-import=luaparser `
            --hidden-import=pyvis `
            --hidden-import=PySide6 `
            --hidden-import=PySide6.QtWebEngineCore `
            --hidden-import=PySide6.QtWebEngineWidgets `
            --hidden-import=PySide6.QtWebChannel `
            --collect-data=pyvis `
            lus4n/gui.py
          
          # Package command-line application with explicit includes
          Write-Host "Packaging command-line application..." -ForegroundColor Green
          pyinstaller --clean --noconfirm --onedir --name "lus4n-cli" --additional-hooks-dir=hooks `
            --hidden-import=xxhash `
            --hidden-import=networkx `
            --hidden-import=joblib `
            --hidden-import=tqdm `
            --hidden-import=loguru `
            --hidden-import=luaparser `
            lus4n/cli.py
          
          # Check generated executable files
          $guiExe = ".\dist\lus4n-gui\lus4n-gui.exe"
          $cliExe = ".\dist\lus4n-cli\lus4n-cli.exe"
          
          if (!(Test-Path $guiExe) -or !(Test-Path $cliExe)) {
              Write-Host "Packaging failed, cannot find generated executable files!" -ForegroundColor Red
              exit 1
          }
          
          # Create release packages
          mkdir releases -Force
          Compress-Archive -Path ".\dist\lus4n-gui\*" -DestinationPath ".\releases\lus4n-gui-windows.zip" -Force
          Compress-Archive -Path ".\dist\lus4n-cli\*" -DestinationPath ".\releases\lus4n-cli-windows.zip" -Force

      - name: Create release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          name: lus4n ${{ github.ref_name }}
          body: |
            lus4n ${{ github.ref_name }} release
            
            ### Includes:
            - Windows GUI version (lus4n-gui-windows.zip)
            - Windows command-line version (lus4n-cli-windows.zip)
            
            ### Dependency updates:
            - All dependencies have been updated to the latest stable version
          files: |
            ./releases/lus4n-gui-windows.zip
            ./releases/lus4n-cli-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}