name: 自动构建发布

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install xxhash==3.5.0
        shell: pwsh

      - name: 创建spec文件
        run: |
          $gui_spec = "lus4n-gui.spec"
          $cli_spec = "lus4n-cli.spec"
          
          # 创建GUI的spec文件
          pyinstaller --name lus4n-gui --onefile --noconsole --hidden-import xxhash --hidden-import networkx --hidden-import joblib --hidden-import tqdm --hidden-import loguru --hidden-import luaparser --hidden-import pyvis --hidden-import PySide6 --hidden-import PySide6.QtWebEngineCore --hidden-import PySide6.QtWebEngineWidgets --hidden-import PySide6.QtWebChannel lus4n/gui.py --specpath .
          
          # 创建CLI的spec文件
          pyinstaller --name lus4n-cli --onefile --console --hidden-import xxhash --hidden-import networkx --hidden-import joblib --hidden-import tqdm --hidden-import loguru --hidden-import luaparser lus4n/cli.py --specpath .
        shell: pwsh

      - name: 使用PyInstaller打包
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
          spec: lus4n-gui.spec

      - name: 使用PyInstaller打包CLI
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
          spec: lus4n-cli.spec

      - name: 准备发布文件
        run: |
          mkdir releases -Force
          
          if (Test-Path "dist\windows\lus4n-gui.exe") {
            Compress-Archive -Path "dist\windows\lus4n-gui.exe" -DestinationPath "releases\lus4n-gui-windows.zip" -Force
            Write-Host "GUI版本打包成功"
          } else {
            Write-Host "找不到GUI可执行文件" -ForegroundColor Red
          }
          
          if (Test-Path "dist\windows\lus4n-cli.exe") {
            Compress-Archive -Path "dist\windows\lus4n-cli.exe" -DestinationPath "releases\lus4n-cli-windows.zip" -Force
            Write-Host "CLI版本打包成功"
          } else {
            Write-Host "找不到CLI可执行文件" -ForegroundColor Red
          }
        shell: pwsh

      - name: 发布版本
        uses: softprops/action-gh-release@v1
        with:
          name: lus4n ${{ github.ref_name }}
          body: |
            lus4n ${{ github.ref_name }} 发布
            
            ### 包含内容:
            - Windows GUI版本 (lus4n-gui-windows.zip)
            - Windows 命令行版本 (lus4n-cli-windows.zip)
            
            ### 修复:
            - 修复了xxhash模块缺失导致程序无法启动的问题
          files: |
            ./releases/lus4n-gui-windows.zip
            ./releases/lus4n-cli-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}